name: pce-pinns
channels:
  - defaults
dependencies:
  - python=3.8.5
  - numpy=1.19.2
  - pytorch # Tested with 1.7.1
  - cudatoolkit=11.0.221
  - pandas=1.2.1
  - scikit-learn=0.23.2
  - matplotlib=3.3.2
  - tqdm=4.55.1